-- Seed Plastics (Plexiglas, PVC)

INSERT INTO public.materials (category, code, name_en, name_ru, name_lv, thickness_options, metadata)
VALUES 
-- PLEXIGLAS materials
('Plastics', 'PLEXIGLAS_XT_0F00', 'PLEXIGLAS® XT Clear', 'PLEXIGLAS® XT Прозрачный', 'PLEXIGLAS® XT Caurspīdīgs', '[1.5, 2, 3, 4, 5, 6, 8, 10, 12, 15, 20, 25]', '{"brand": "PLEXIGLAS®", "series": "XT", "colorCode": "0F00", "colorName": "Clear", "type": "extruded", "transmittance": "92%", "properties": {"transparent": true, "uvAbsorbent": true, "weatherResistant": true, "tempResistance": "70°C"}, "standardSize": "3050x2050mm", "hex": "#FFFFFF", "applications": ["Glazing", "LED applications", "Shopfitting"]}'),
('Plastics', 'PLEXIGLAS_XT_WN071', 'PLEXIGLAS® XT White Opal', 'PLEXIGLAS® XT Белый Опал', 'PLEXIGLAS® XT Baltais Opāls', '[2, 3, 4, 5, 6, 8, 10]', '{"brand": "PLEXIGLAS®", "series": "XT", "colorCode": "WN071", "colorName": "White Opal", "type": "extruded", "transmittance": "30%", "properties": {"translucent": true, "uvAbsorbent": true, "weatherResistant": true, "highGloss": true, "tempResistance": "70°C"}, "standardSize": "3050x2050mm", "hex": "#F5F5F0", "applications": ["Illuminated advertising", "Light diffusion", "Signage"]}'),
('Plastics', 'PLEXIGLAS_GS_WH10', 'PLEXIGLAS® GS White Opaque', 'PLEXIGLAS® GS Белый Непрозрачный', 'PLEXIGLAS® GS Baltais Nepārredzams', '[3, 4, 5, 6, 8, 10, 12, 15, 20]', '{"brand": "PLEXIGLAS®", "series": "GS", "colorCode": "WH10", "colorName": "White Opaque", "type": "cast", "transmittance": "0%", "properties": {"opaque": true, "uvAbsorbent": true, "weatherResistant": true}, "standardSize": "3050x2030mm", "hex": "#FFFFFF", "applications": ["Signage", "Furniture", "Displays"]}'),
('Plastics', 'PLEXIGLAS_XT_1N870', 'PLEXIGLAS® XT Yellow', 'PLEXIGLAS® XT Желтый', 'PLEXIGLAS® XT Dzeltens', '[2, 3, 4, 5, 6, 8, 10]', '{"brand": "PLEXIGLAS®", "series": "XT", "colorCode": "1N870", "colorName": "Yellow", "type": "extruded", "transmittance": "20%", "properties": {"translucent": true, "uvAbsorbent": true, "colorFast": true}, "standardSize": "3050x2050mm", "hex": "#FFD700", "applications": ["Colored signage", "Displays"]}'),
('Plastics', 'PLEXIGLAS_XT_3N570', 'PLEXIGLAS® XT Red', 'PLEXIGLAS® XT Красный', 'PLEXIGLAS® XT Sarkans', '[2, 3, 4, 5, 6, 8, 10]', '{"brand": "PLEXIGLAS®", "series": "XT", "colorCode": "3N570", "colorName": "Red", "type": "extruded", "transmittance": "15%", "properties": {"translucent": true, "uvAbsorbent": true, "colorFast": true}, "standardSize": "3050x2050mm", "hex": "#DC143C", "applications": ["Colored signage", "Displays"]}'),

-- PVC Foam materials
('Plastics', 'PVC_FOAM_WHITE', 'PVC Foam Board White', 'ПВХ Пенопласт Белая', 'PVC Putu Plāksne Balta', '[3, 5, 8, 10, 12, 15, 18, 19]', '{"brand": "Palight®", "name": "PVC Foam Board White", "type": "foam", "density": "0.45-0.57 g/cm³", "finish": "matte", "properties": {"lightweight": true, "weatherResistant": true, "easyToMachine": true, "paintable": true, "waterproof": true}, "standardSize": "1220x2440mm", "hex": "#FFFFFF", "fireRating": "UK Class 1", "serviceTemp": "-10 to 55°C", "applications": ["Signage", "Displays", "Exhibition stands"]}'),
('Plastics', 'PVC_FOAM_BLACK', 'PVC Foam Board Black', 'ПВХ Пенопласт Черная', 'PVC Putu Plāksne Melna', '[3, 5, 8, 10, 15, 18]', '{"brand": "Palight®", "name": "PVC Foam Board Black", "type": "foam", "density": "0.50 g/cm³", "finish": "matte", "properties": {"lightweight": true, "weatherResistant": true, "easyToMachine": true, "waterproof": true}, "standardSize": "1220x2440mm", "hex": "#000000", "applications": ["Signage", "Displays"]}'),
('Plastics', 'PVC_FOAM_RED', 'PVC Foam Board Red', 'ПВХ Пенопласт Красная', 'PVC Putu Plāksne Sarkana', '[5, 8, 10, 15, 18]', '{"brand": "Palight®", "name": "PVC Foam Board Red", "type": "foam", "density": "0.50 g/cm³", "finish": "gloss", "properties": {"lightweight": true, "weatherResistant": true, "colorFast": true, "waterproof": true}, "standardSize": "1220x2440mm", "hex": "#DC143C", "applications": ["Signage", "Displays", "Point of sale"]}');
