-- Seed Oracal 8500 Translucent Cal Films
-- Source: 54 Colours provided by user

INSERT INTO public.materials (category, code, name_en, thickness_options, metadata)
VALUES 
('Films', 'ORACAL_010S', 'White', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [231, 232, 229]}'::jsonb),
('Films', 'ORACAL_025S', 'Brimstone yellow', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [209, 198, 0]}'::jsonb),
('Films', 'ORACAL_021S', 'Yellow', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [255, 207, 0]}'::jsonb),
('Films', 'ORACAL_013S', 'Zinc yellow', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [243, 195, 0]}'::jsonb),
('Films', 'ORACAL_020S', 'Golden yellow', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [250, 173, 0]}'::jsonb),
('Films', 'ORACAL_207S', 'Ochre yellow', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [225, 165, 41]}'::jsonb),
('Films', 'ORACAL_034S', 'Orange', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [224, 84, 0]}'::jsonb),
('Films', 'ORACAL_330S', 'Fox red', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [200, 36, 17]}'::jsonb),
('Films', 'ORACAL_323S', 'Coral red', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [211, 39, 59]}'::jsonb),
('Films', 'ORACAL_032S', 'Light red', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [204, 49, 28]}'::jsonb),
('Films', 'ORACAL_329S', 'Carnation red', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [195, 5, 14]}'::jsonb),
('Films', 'ORACAL_016S', 'Crimson', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [207, 17, 10]}'::jsonb),
('Films', 'ORACAL_031S', 'Red', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [193, 28, 19]}'::jsonb),
('Films', 'ORACAL_017S', 'Cherry red', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [165, 0, 14]}'::jsonb),
('Films', 'ORACAL_030S', 'Dark red', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [119, 0, 23]}'::jsonb),
('Films', 'ORACAL_085S', 'Pale pink', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [223, 142, 143]}'::jsonb),
('Films', 'ORACAL_413S', 'Light pink', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [211, 97, 177]}'::jsonb),
('Films', 'ORACAL_041S', 'Pink', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [179, 0, 106]}'::jsonb),
('Films', 'ORACAL_008S', 'Heather red', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [118, 6, 48]}'::jsonb),
('Films', 'ORACAL_040S', 'Violet', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [100, 0, 92]}'::jsonb),
('Films', 'ORACAL_403S', 'Light violet', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [94, 34, 135]}'::jsonb),
('Films', 'ORACAL_012S', 'Lilac', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [69, 3, 87]}'::jsonb),
('Films', 'ORACAL_527S', 'Pastel blue', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [87, 145, 173]}'::jsonb),
('Films', 'ORACAL_053S', 'Light blue', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [0, 142, 213]}'::jsonb),
('Films', 'ORACAL_052S', 'Azure blue', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [0, 98, 183]}'::jsonb),
('Films', 'ORACAL_051S', 'Gentian blue', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [0, 89, 172]}'::jsonb),
('Films', 'ORACAL_528S', 'Grey blue', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [0, 101, 157]}'::jsonb),
('Films', 'ORACAL_005S', 'Middle blue', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [5, 57, 162]}'::jsonb),
('Films', 'ORACAL_006S', 'Intensive blue', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [0, 45, 117]}'::jsonb),
('Films', 'ORACAL_049S', 'King blue', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [36, 4, 123]}'::jsonb),
('Films', 'ORACAL_542S', 'Caribic blue', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [20, 36, 121]}'::jsonb),
('Films', 'ORACAL_065S', 'Cobalt blue', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [33, 0, 102]}'::jsonb),
('Films', 'ORACAL_007S', 'Dark blue', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [37, 35, 95]}'::jsonb),
('Films', 'ORACAL_541S', 'Dark turquoise', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [0, 83, 115]}'::jsonb),
('Films', 'ORACAL_066S', 'Turquoise blue', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [0, 139, 150]}'::jsonb),
('Films', 'ORACAL_054S', 'Turquoise', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [0, 172, 146]}'::jsonb),
('Films', 'ORACAL_062S', 'Light green', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [0, 153, 53]}'::jsonb),
('Films', 'ORACAL_063S', 'Lime-tree green', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [74, 182, 0]}'::jsonb),
('Films', 'ORACAL_009S', 'Middle green', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [0, 157, 104]}'::jsonb),
('Films', 'ORACAL_614S', 'Reed green', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [0, 115, 50]}'::jsonb),
('Films', 'ORACAL_068S', 'Grass green', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [0, 110, 56]}'::jsonb),
('Films', 'ORACAL_618S', 'Dragon green', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [0, 63, 66]}'::jsonb),
('Films', 'ORACAL_087S', 'Emerald', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [0, 120, 50]}'::jsonb),
('Films', 'ORACAL_060S', 'Dark green', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [0, 62, 41]}'::jsonb),
('Films', 'ORACAL_070S', 'Black', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [27, 29, 32]}'::jsonb),
('Films', 'ORACAL_074S', 'Middle grey', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [135, 143, 143]}'::jsonb),
('Films', 'ORACAL_076S', 'Telegrey', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [155, 161, 167]}'::jsonb),
('Films', 'ORACAL_072S', 'Light grey', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [198, 201, 202]}'::jsonb),
('Films', 'ORACAL_805S', 'Ivory', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [227, 213, 179]}'::jsonb),
('Films', 'ORACAL_011S', 'Pale brown', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [223, 187, 135]}'::jsonb),
('Films', 'ORACAL_081S', 'Light brown', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [180, 137, 89]}'::jsonb),
('Films', 'ORACAL_088S', 'Coffee brown', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [70, 41, 33]}'::jsonb),
('Films', 'ORACAL_090S', 'Silver grey', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [125, 129, 132]}'::jsonb),
('Films', 'ORACAL_091S', 'Gold', '[]'::jsonb, '{"brand": "Oracal", "series": "8500", "finish": "satin gloss", "rgb": [144, 127, 68]}'::jsonb);