#!/bin/bash
# Script to seed the database with initial data

echo "Seeding the OMS database with initial data..."

echo "Unfortunately, the Supabase CLI doesn't support direct file execution for remote databases."
echo ""
echo "Please use one of the following methods to seed your database:"
echo ""
echo "Method 1: Using Supabase Dashboard SQL Editor"
echo "1. Go to your Supabase dashboard: https://app.supabase.com/project/YOUR_PROJECT_ID/editor"
echo "2. Copy and paste the content of scripts/seed_database.sql"
echo "3. Click 'Run'"
echo ""
echo "Method 2: Using a local PostgreSQL client (if you have the connection string)"
echo "1. Get your database connection string from the Supabase dashboard"
echo "2. Use a PostgreSQL client like pgAdmin, DBeaver, or command line psql"
echo "3. Connect using your connection string"
echo "4. Execute the SQL commands from scripts/seed_database.sql"
echo ""
echo "The seed script includes:"
echo "- Essential materials data for plastics, metals, colors and films"
echo "- First admin user with credentials: Slaff / Slaff181188"
echo "- Sample draft orders"
echo "- Sample profile templates"
echo "- Sample audit log entries"