#!/bin/bash
# scripts/setup-production.sh

echo "🚀 OMS Production Setup"
echo "======================="
echo ""

# Check if .env exists
if [ -f .env ]; then
    echo "⚠️  .env file already exists"
    read -p "Overwrite? (yes/no): " confirm
    if [ "$confirm" != "yes" ]; then
        echo "Aborted."
        exit 0
    fi
fi

echo "Generating secure secrets..."

# Generate secrets
SESSION_SECRET=$(openssl rand -base64 32)
JWT_SECRET=$(openssl rand -base64 32)
ADMIN_PASSWORD=$(openssl rand -base64 24)

# Create .env file
cat > .env <<EOF
# Generated by setup-production.sh on $(date)
NODE_ENV=production

# Database - UPDATE THIS
DATABASE_URL=postgresql://user:password@host:5432/database

# Supabase - UPDATE THESE
SUPABASE_URL=https://your-project.supabase.co
SUPABASE_ANON_KEY=your-anon-key-here
SUPABASE_SERVICE_ROLE_KEY=your-service-role-key-here

# Generated Secrets
SESSION_SECRET=${SESSION_SECRET}
JWT_SECRET=${JWT_SECRET}

# Sentry (optional)
# SENTRY_DSN=

# AI Features (optional)
# DASHSCOPE_API_KEY=
EOF

echo ""
echo "✅ .env file created with secure secrets"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📝 NEXT STEPS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Update DATABASE_URL in .env with your database credentials"
echo "2. Update SUPABASE_* variables in .env"
echo "3. (Optional) Add SENTRY_DSN for error monitoring"
echo "4. Run: npm run build"
echo "5. Run: npm run preview"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔑 Generated Admin Password (save securely):"
echo "${ADMIN_PASSWORD}"
echo ""
